### ISSUE TITLE
Topic Page: Create Topic Wizard (show all available options OFF)

### ISSUE THREAD

**Issue by christiemolloy** [bf2fc6cc711aee1a0c2a/uxd-mk-data-plane-ui#4]
Complete Create Topic wizard with "Show all available options" turned off.
@jgiardino I only see one screen related to the "Create Topic" page. Are there more designs for the other options underneath Topic Name?

https://marvelapp.com/prototype/26598gag/screen/73803096

**Comment by jgiardino** [comment]
@lboehling - Do you have examples of the other pages in the Create Topic wizard?

**Comment by jgiardino** [comment]
@christiemolloy for this and issue #5, how easy is it to have a shared app state, so that values they entered in this variation of the Create flow are persistent if they toggle to the other variation of the Create flow? I had included a comment in #8 that values the user enters should not persist after hitting the Save button, and so I'd also expect that in this case. But across all the Create pages until they hit submit, it would be nice to persist data if possible and not time consuming to do. If it is a lot of extra work, though, we should discuss before committing to it.

Also, @lboehling are you aware of any behavior associated with the switch that shows all available settings? Is the expectation that settings in the basic flow persist when switching to the advanced flow? I'm assuming that going from advanced to basic you would lose settings, and also assume that the user would see some confirmation prompt (i.e. "some settings specified will be lost"), but not sure if there are designs for this flow. If there are, it might be nice to add an issue to capture this, so that we can observe users' reactions if they make this switch.

**Comment by christiemolloy** [comment]
Could you further explain what this means and show screenshots: "so that values they entered in this variation of the Create flow are persistent if they toggle to the other variation of the Create flow?"

We can definitely store the state data across all of the create pages and pass these states through to the save button. Its just if they did a hard refresh that the states would refresh.

**Comment by jgiardino** [comment]
> We can definitely store the state data across all of the create pages and pass these states through to the save button. Its just if they did a hard refresh that the states would refresh.

Yeah, that's totally fine. Should storing app state be a separate issue? I'd like to get @amysueg's opinion on whether this is critical for the user test, or something we can just identify as not functional in the prototype when user testing. 

> Could you further explain what this means and show screenshots: "so that values they entered in this variation of the Create flow are persistent if they toggle to the other variation of the Create flow?"

I could be making assumptions about expected behavior, so bubbling this question up to @lboehling.

@lboehling, Do you know what the expectation is when a user toggles the switch in this example to "Show all available options", specifically wrt common inputs? For example, in the first screen, if I enter a topic name, then toggle the switch, is that name maintained? And is it maintained if they go back? Is there a warning message that displays when the user toggles it one way or the other, warning that info they entered could be lost?

![image](https://user-images.githubusercontent.com/21063328/97489805-65b19f80-1936-11eb-8c78-6ec0b60deaaf.png)


Without knowing what the original design documentation says, I would assume that switching from a `not:all available options` to `all available options` mode, that the options with values are maintained. But when switching from `all available options` to `not:all available options` that the options not present in the latter are cleared, and the user is notified that this will happen in a confirmation prompt.

If that's the case, then I think the confirmation prompt should be captured as part of a separate issue. This could be something we want to capture the users' reaction on.

**Comment by lboehling** [comment]
> @lboehling - Do you have examples of the other pages in the Create Topic wizard?

@christiemolloy Uploaded the rest of the basic wizard steps to the marvel: https://marvelapp.com/prototype/26598gag/screen/74015206

> @lboehling, Do you know what the expectation is when a user toggles the switch in this example to "Show all available options", specifically wrt common inputs? For example, in the first screen, if I enter a topic name, then toggle the switch, is that name maintained? And is it maintained if they go back? Is there a warning message that displays when the user toggles it one way or the other, warning that info they entered could be lost?

I'm not sure what the expectation is here, and as far as I know it wasn't called out in any of the design documentation they sent to us. I agree with your assumption though @jgiardino
